### PR TITLE
fix: add @babel/plugin-transform-runtime

### PR DESCRIPTION
**Pull request by kamranayub**
Tried to consume this package but was running into `"regeneratorRuntime" is not defined errors". If I understand correctly, libraries using async/await should include the runtime helpers for environments that don't natively support async/await.

Making this change and doing a local publish allows me to use the library so this is working for me.

## Changes

- Add `@babel/plugin-transform-runtime` with `runtimeHelpers: true` Rollup configuration
- Add `.nvmrc` for folks using NVM

## TODO

- ~Not sure about `package-lock.json`, when I run `npm install` it switches everything to exact versioning instead of `^` so it results in a massive change which is not ideal. Still figuring that out (my guess is different npm versions or config).~

### CODE REVIEW

**Comment by OllieJennings** [comment]
Thanks for this @kamranayub, ill have a look today.

**Comment by kamranayub** [comment]
@OllieJennings Thanks, you may need to run `npm install` on my branch and push your package-lock, just so it matches what you'd expect since I don't want to accidentally mess it up due to my Node/npm versions.

**Comment by OllieJennings** [comment]
@kamranayub I'm thinking about fully converting this project to TypeScript in the next few days, so i'll merge in your typings Branch PR/MR and then remove babel in the conversion if that sounds good?

**Comment by kamranayub** [comment]
@OllieJennings sure thing!

**Comment by kamranayub** [comment]
@OllieJennings Have you started the conversion yet? If not or if you are interested, I am happy to provide assistance there and get a draft up or work from a branch if you have one in my fork. I would *love* to uptake this in our project this week but I am a bit blocked by the babel issue with our Jest tests 👍 Right now I have a local copy of the package aliased in and it works but would prefer an official stable/pre-release from npm to depend on.

**Comment by OllieJennings** [comment]
@kamranayub Apologies, yes the conversion has started. Let me see if l can get it finished today.

**Comment by OllieJennings** [comment]
@kamranayub apologies for delay, basically finished the re-write now, just cleaning up some of the tests and will notify you of the PR

**Comment by kamranayub** [comment]
@OllieJennings Would you want to publish your branch? That way I could reference your new implementation even if you don't publish right away. I'm happy to help in any way as well with tests if you need it!

**Comment by outdooricon** [comment]
I'm also pretty excited for this fix. Any progress @OllieJennings ?

**Comment by kamranayub** [comment]
Just FYI I am using a private fork with this change so that I could keep moving along but please let me know if there's anything I can do to help get this in or convert to TypeScript. 🙏

**Comment by stuarthadfieldglobality** [comment]
Bump @OllieJennings also running into this issue, can we get a progress report here?

**Comment by stuarthadfieldglobality** [comment]
Otherwise @kamranayub would you be willing to publish the version you have running onto a public registry?

**Comment by kamranayub** [comment]
Yes, I could publish it under my scope just so others can access it if needed. It's essentially this PR packaged up with a different name/version published to internal registry.

**Pull request closed without merging**
